build: spring-kafka-test 버전 제거
- Caused by: java.lang.IllegalStateException: java.lang.NoSuchMethodError: 'java.lang.String kafka.server.KafkaConfig.DeleteTopicEnableProp()' 발생